# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Start_Stop.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Visionary(object):
    def setupUi(self, Visionary):
        Visionary.setObjectName("Visionary")
        Visionary.resize(439, 359)
        Visionary.setStyleSheet("QPushButton{\n"
                                "    border-radius: 15px;\n"
                                "    border-right: 1px solid #aaaaaa;\n"
                                "    border-bottom: 1px solid #aaaaaa;\n"
                                "}\n"
                                "\n"
                                "QPushButton:enabled {\n"
                                "    background-color:blue ;\n"
                                "    color: white;\n"
                                "}\n"
                                "\n"
                                "QPushButton:pressed {\n"
                                "    background-color: #0d2f72;\n"
                                "    color: #fffffe;\n"
                                "}\n"
                                "\n"
                                "QPushButton:hover:!pressed {\n"
                                "    background-color: #E1F4FF;\n"
                                "    color: #0c2f70;\n"
                                "}\n"
                                "\n"
                                "QPushButton:disabled {\n"
                                "    background-color: #aaaaaa;\n"
                                "    color: #ffffff;\n"
                                "}\n"
                                "\n"
                                "")
        self.layoutWidget = QtWidgets.QWidget(Visionary)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(Visionary)
        self.frame_3.setGeometry(QtCore.QRect(10, 0, 421, 351))
        self.frame_3.setMinimumSize(QtCore.QSize(19, 14))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.Start = QtWidgets.QPushButton(self.frame_3)
        self.Start.setGeometry(QtCore.QRect(210, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Start.setFont(font)
        self.Start.setAutoFillBackground(False)
        self.Start.setStyleSheet("Background:rgb(120, 185, 235);")
        self.Start.setObjectName("Start")
        self.Stop = QtWidgets.QPushButton(self.frame_3)
        self.Stop.setGeometry(QtCore.QRect(310, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Stop.setFont(font)
        self.Stop.setStyleSheet("Background:rgb(120, 185, 235);")
        self.Stop.setObjectName("Stop")
        self.TEXT = QtWidgets.QTextBrowser(self.frame_3)
        self.TEXT.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("HP Simplified Hans")
        self.TEXT.setFont(font)
        self.TEXT.setObjectName("TEXT")
        self.imgLabel = QtWidgets.QLabel(self.frame_3)
        self.imgLabel.setGeometry(QtCore.QRect(10, 50, 391, 281))
        self.imgLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.imgLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imgLabel.setLineWidth(5)
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")

        self.retranslateUi(Visionary)
        self.Stop.clicked.connect(Visionary.exec)  # type: ignore
        self.Start.clicked.connect(Visionary.exec)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Visionary)

    def retranslateUi(self, Visionary):
        _translate = QtCore.QCoreApplication.translate
        # Visionary.setWindowTitle(_translate("Visionary", "Dialog"))
        Visionary.setWindowTitle(_translate("Visionary", "Visionary"))
        self.Start.setText(_translate("Visionary", "Start"))
        self.Stop.setText(_translate("Visionary", "Stop"))
        self.TEXT.setHtml(_translate("Visionary", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                     "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                     "p, li { white-space: pre-wrap; }\n"
                                     "</style></head><body style=\" font-family:\'HP Simplified Hans\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
                                     "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Visionary = QtWidgets.QDialog()
    ui = Ui_Visionary()
    ui.setupUi(Visionary)
    Visionary.show()
    sys.exit(app.exec_())
